### ISSUE TITLE
nginx fails on clear container due to stderr/stdout redirection error

### ISSUE THREAD

**Issue by mcastelino** [01org/cc-oci-runtime#129]
ngnix fails to run with the following error

```
docker run -it nginx /bin/bash
root@aeb7593fc548:/# nginx -g "daemon off;"
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (1: Operation not permitted)
2016/08/17 02:25:36 [emerg] 211#211: open() "/var/log/nginx/error.log" failed (1: Operation not permitted)

```

This seems to be an error with std* handling

```
root@aeb7593fc548:/# ls -l /var/log/nginx/
total 0
lrwxrwxrwx 1 root root 11 Jun  1 18:00 access.log -> /dev/stdout
lrwxrwxrwx 1 root root 11 Jun  1 18:00 error.log -> /dev/stderr

root@aeb7593fc548:/# ls -l /dev
total 0
lrwxrwxrwx 1 root root   13 Aug 17 02:25 fd -> /proc/self/fd
crw-rw-rw- 1 root root 1, 7 Aug 17 02:25 full
drwxr-xr-x 2 root root    0 Aug 17 02:25 hugepages
lrwxrwxrwx 1 root root   28 Aug 17 02:25 log -> /run/systemd/journal/dev-log
drwxrwxrwt 2 root root   40 Aug 17 02:25 mqueue
crw-rw-rw- 1 root root 1, 3 Aug 17 02:25 null
lrwxrwxrwx 1 root root    8 Aug 17 02:25 ptmx -> pts/ptmx
drwxr-xr-x 2 root root    0 Aug 17 02:25 pts
crw-rw-rw- 1 root root 1, 8 Aug 17 02:25 random
drwxrwxrwt 2 root root   40 Aug 17 02:25 shm
lrwxrwxrwx 1 root root   15 Aug 17 02:25 stderr -> /proc/self/fd/2
lrwxrwxrwx 1 root root   15 Aug 17 02:25 stdin -> /proc/self/fd/0
lrwxrwxrwx 1 root root   15 Aug 17 02:25 stdout -> /proc/self/fd/1
crw-rw-rw- 1 root root 5, 0 Aug 17 02:25 tty
crw-rw-rw- 1 root root 1, 9 Aug 17 02:25 urandom
crw-rw-rw- 1 root root 1, 5 Aug 17 02:25 zero

```

**Comment by mcastelino** [comment]
@grahamwhaley @sameo As a workaround you can use a slightly modified nginx container that has the softlinks removed
access.log -> /dev/stdout
error.log -> /dev/stderr

https://hub.docker.com/r/mcastelino/nginx/

**Comment by amshinde** [comment]
A quick check with a runc container shows the same redirections. While starting the containers interactively,

On runc:
```
root@3637bdf3b9a8:/# ls -la /var/log/nginx/   
total 8
drwxr-xr-x 2 root root 4096 Aug 17 16:20 .
drwxr-xr-x 1 root root 4096 Aug 17 16:20 ..
lrwxrwxrwx 1 root root   11 Jun  1 18:00 access.log -> /dev/stdout
lrwxrwxrwx 1 root root   11 Jun  1 18:00 error.log -> /dev/stderr
root@3637bdf3b9a8:/# echo hello>/var/log/nginx/error.log 
hello
```

On clear-containers:
```
root@2d1fa1f43f11:/# ls -la /var/log/nginx/
total 8
drwxr-xr-x 2 root root 4096 Aug 17 16:20 .
drwxr-xr-x 1 root root 4096 Aug 17 16:20 ..
lrwxrwxrwx 1 root root   11 Jun  1 18:00 access.log -> /dev/stdout
lrwxrwxrwx 1 root root   11 Jun  1 18:00 error.log -> /dev/stderr
root@2d1fa1f43f11:/# echo hello>/var/log/nginx/error.log 
bash: /var/log/nginx/error.log: Operation not permitted
```

**Comment by amshinde** [comment]
I had been looking at the systemd service used to for executing the workload. Currently we have PrivateDevices=Yes in the unit file. After disabling this, the above error is no longer seen.

**Comment by amshinde** [comment]
jodh-intel  any input on this?

**Comment by jodh-intel** [comment]
I'm not sure we want to remove `PrivateDevices=`. The systemd docs aren't totally clear, but to me they suggest the following might work:

```
PrivateDevices=yes
DevicePolicy=strict
DeviceAllow=/dev/null rw
DeviceAllow=/dev/zero rw
DeviceAllow=/dev/full rw
DeviceAllow=/dev/random r
DeviceAllow=/dev/urandom r
DeviceAllow=/dev/stdin r
DeviceAllow=/dev/stdout w
DeviceAllow=/dev/stderr w
```

**Comment by amshinde** [comment]
Setting PrivateDevices=Yes, sets DevicePolicy=Closed according to the systemd docs . So the two settings conflict.
What was required to fix the issue was adding
 "DeviceAllow=/dev/console rw"
This allows access to the system console  /dev/console in the VM, although it doesn't really create a console node in the /dev namespace.

'''
root@1c0bacfc0105:/# readlink /proc/self/fd/1
/dev/console
'''

From the Fedora docs:
"When PrivateDevices=yes is set in the [Service] section of a systemd service unit file, the processes run for the service will run in a private file system namespace where /dev is replaced by a minimal version that only includes the device nodes /dev/null, /dev/zero, /dev/full, /dev/urandom, /dev/random, /dev/tty as well as the submounts /dev/shm, /dev/pts, /dev/mqueue, /dev/hugepages, and the /dev/stdout, /dev/stderr, /dev/stdin symlinks. No device nodes for physical devices will be included however. Furthermore, the CAP_MKNOD capability is removed. Finally, the "devices" cgroup controller is used to ensure that no access to device nodes except the listed ones is possible. "

 With PrivateDevices=yes, sets up the pseudo urandom and random devices, which are missing otherwise which would break commands that use them. (since we don’t mount /dev from the VM )

**Comment by jodh-intel** [comment]
Great - please could you update `./system/container-workload.service` in `clr-systemd-config` accordingly.

**Comment by amshinde** [comment]
Sure

**Comment by amshinde** [comment]
This should be available in the next release of clear container image

**Comment by GabyCT** [comment]
This is working now, it was verified using clear-10360-containers.img.
root@2a81123ab879:/# ls -la /var/log/nginx/
total 8
drwxr-xr-x 2 root root 4096 Aug 23 18:51 .
drwxr-xr-x 5 root root 4096 Aug 23 18:51 ..
lrwxrwxrwx 1 root root   11 Aug 23 18:51 access.log -> /dev/stdout
lrwxrwxrwx 1 root root   11 Aug 23 18:51 error.log -> /dev/stderr
root@2a81123ab879:/# echo hello>/var/log/nginx/error.log
hello
