### ISSUE TITLE
(pseudo)tty not properly setup with the -t option

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#133]
```
$ docker run  -t debian tty
/dev/console
$ docker run --runtime cc -t debian tty
not a tty
```

**Comment by amshinde** [comment]
While experimenting with systemd options for another bug, I realised that if we mount the /dev from the VM into the workload and avoid creating a new dev namespace with PrivateDevices=Yes, the above issue is resolved. This needs some more investigation to rootcause what is happening.
If we go with the above, we can restrict access to just certain pseudo devices using systemd cgroup mechanism(DevicePolicy=Strict, DeviceAllow..), although all the devices will be visible to the workload since we don't change dev namespace.

**Comment by dlespiau** [comment]
I arrived at the same conclusion and did find we were missing /dev/console as well, haven't checked it that was enough for that one as well.

**Comment by chavafg** [comment]
added test on #523

**Comment by chavafg** [comment]
closing this issue as tests are already merged.
