### ISSUE TITLE
Document host kernel requirements 

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#227]
Document the minimal kernel version needed to run CC2.0 and its needed configuration (kvm, vhost ... )

**Comment by jodh-intel** [comment]
I wonder if we could enhance [1] so that you could run it, passing it the kernel config file for any checks that cannot be performed on the running system?:

```
$ ./clear-linux-check-config.sh --kernel-config /boot/config host
```

That way, the documentation would just be "run the script above" :-) That approach would also avoid us having to keep the doc and the script "in sync".

(Note: If we decide to take the programmatic approach, we should involve Gabriel too).

**Comment by jcvenegas** [comment]
cc-runtime provide a better way to know if is possible or not
