### ISSUE TITLE
Daemon support for hyperstart

### ISSUE THREAD

**Issue by dlespiau** [01org/cc-oci-runtime#257]
We need hyperstart to act like a daemon (and not an init system) when launched inside our mini-OS VM.

Current progress: https://github.com/dlespiau/hyperstart/tree/20160912-daemon

**Comment by jcvenegas** [comment]
WIP: Change binary name to hyperstart  and add service file for systemd.
It is required start hyperstart service at  container.target

**Comment by dlespiau** [comment]
@jcvenegas do you have any update on the --with-hyperstart-name option (or whatever we end up calling it) and the systemd integration? do you have anymore commits? I'd love to send hyper the daemon PR (still need to rework my patches as well) this week.

**Comment by jcvenegas** [comment]
@dlespiau, I did not update them , let me add  --with-hyperstart-name

**Comment by dlespiau** [comment]
So, maybe  `--program-transform-name='s/^init$/hyperstart/;'` is the best option here.

**Comment by jcvenegas** [comment]
@dlespiau yup renaming is the only way I see it works well ... I tried  to use " --with-binary-option" to build the binary depending on the variable, but it is  needed to  define EXTRA_PROGRAMS variable with a  list of programs that will be built, but sadly does not support a configure variable substitution. 

For renaming @devimc  came up with an idea . Use --with-binary-name but instead of build the binary with the "--with-binary-name" value, use "install-exec-hook" hook target to rename "init" file to a custom name file. This way we still have a variable with the daemon binary file and  we can create correctly systemd service pointing to the right renamed file.

**Comment by jcvenegas** [comment]
Other way I think we could  tackle rename init binary is adding a flag --with-daemon-support (or --without-init-support) with we can do:

Add a macro to the source code for parts of code that only will be done in int mode.
In both cases ( daemon mode or init mode) built the binary with the name of hyperstart but in the case of init mode make a symlink of the /bin/hyperstart binary to init

**Comment by jcvenegas** [comment]
Here is the option using --with-binary-name https://github.com/jcvenegas/hyperstart/commits/binary_name

**Comment by jcvenegas** [comment]
Here is an initial proposal  using --enable-daemon option https://github.com/jcvenegas/hyperstart/commit/eb6225634889d72f434c8c1e3b3bf432fe7f8fc8

**Comment by dlespiau** [comment]
The --enable-daemon option seems close but there still a problem with BINARY_NAME=init (which can be tested before the mv)

I wonder if the following alternative could work as well (or if automake will complain):

hyperstart_sources = /* list of .c .h */
bin_PROGRAMS = $(HYPERSTART)

if ENABLE_DAEMON
HYPERSTART=hyperstart
hyperstart_SOURCES=$(hyperstart_sources)
else
HYPERSTART=init
init_SOURCES=$(hyperstart_sources)
end

**Comment by jcvenegas** [comment]
@dlespiau  branch updated

**Comment by jcvenegas** [comment]
https://github.com/jcvenegas/hyperstart/commit/b80d7ec4a75f53b41271fd9ed525383a5fbfe42a

**Comment by dlespiau** [comment]
PR sent: https://github.com/hyperhq/hyperstart/pull/221

**Comment by dlespiau** [comment]
And this is now merged!
