### ISSUE TITLE
hypervisor.sock file name is not complete using docker

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#283]
When a container is created using docker ,  hypervisor.sock file name  in  state dir  is not complete:

The file is named hypervisor.s instead of hypervisor.sock

To reproduce this run:
docker run -ti debian
 check the container the file name in the container sate dir : 
ls run/opencontainer/containers/CONTAINER_ID/hypervisor.s
instead of : 
/run/opencontainer/containers/CONTAINER_ID/hypervisor.sock

**Comment by jcvenegas** [comment]
the no complete name seems to be related to the path size

**Comment by jodh-intel** [comment]
Confirmed - I've just seen:

```
/run/opencontainer/containers/3c4998a7187ea545c79dcda93e375b26d57c8e139532956de62da897b3ee4f2a/hypervisor.s
```

This is actually a bug in qemu; when passed `-qmp "unix:$path"`, qemu create a Unix domain socket. These sockets are limited to 108 bytes on Linux (see `unix(7)`).  Since the path needs to be terminated, the effective length is 107 bytes. The problem is that although qemu does respect the limit, `unix_listen_saddr()` is not validating the path the user specifies, so qemu ends up silently truncating the value specified to `-qmp "unix:$path"`. This is nasty as if you are relying on QMP, you now have no means to control the VM.

I've attached a minimal patch that performs validation on the path passed to qemu.

But there is also something we can do to avoid hitting this issue anyway - reduce our prefix.

Breaking down the path elements we have:

- `CC_OCI_RUNTIME_DIR_PREFIX` runtime prefix (30 bytes):
```
/run/opencontainer/containers/
```

- docker container name (64 bytes):

```
3c4998a7187ea545c79dcda93e375b26d57c8e139532956de62da897b3ee4f2a
```

- socket filename (16 bytes):

```
/hypervisor.sock
```

Hence:

```
max                  = 107 bytes
total = 30 + 64 + 16 = 110 bytes
surplus              =  -3 bytes (Oops! :-)
```

The current value of `CC_OCI_RUNTIME_DIR_PREFIX` used to be specified by the OCI spec, but was dropped, possibly due to these sorts of issues. For example, `runc` now uses a prefix of `/run/runc/`.

So the obvious improvement we can make to the runtime is to change `CC_OCI_RUNTIME_DIR_PREFIX` to 
`/run/cc-oci-runtime/` (20 bytes, saving 10 bytes), or better `/run/cor/` (9 bytes, saving 21 bytes). Assuming the latter:

```
max                 = 107 bytes
total = 9 + 64 + 16 =  89 bytes
surplus             =  18 bytes (yay! :)
```
[qemu-check-unix-domain-socket-length.patch.txt](https://github.com/01org/cc-oci-runtime/files/489361/qemu-check-unix-domain-socket-length.patch.txt)

**Comment by jodh-intel** [comment]
`/run/cc-oci-runtime` is probably a more reasonable value for `CC_OCI_RUNTIME_DIR_PREFIX` to minimise collision with other apps, particularly since the runtime binary isn't called `cor`.

**Comment by jodh-intel** [comment]
@anthonyzxu - does the attached patch look reasonable to you?

**Comment by grahamwhaley** [comment]
Nice analysis @jodh-intel . The nature of the fix lgtm. Are there any other knock on implications we might need to cater for from changing the path?

**Comment by jodh-intel** [comment]
@grahamwhaley - The runtime directory isn't directly exposed to container managers so that shouldn't be a problem. The only potential issue I can think of is where the runtime package is updated on a system with running containers. Something like:

- User creates a new container via docker.
- Long-running container starts.
- /usr/bin/cc-oci-runtime` is upgraded (and the new version uses `/run/cc-oci-runtime/` rather than `/run/opencontainer/containers/`).
- User tries to stop the long-running container.
  - `docker` => `dockerd` => `containerd` => `cc-oci-runtime delete $container`.
- `cc-oci-runtime` fails as it cannot find `$container` below `/run/cc-oci-runtime/` (because it's below `/run/opencontainer/containers/`).

The safest advice would be to stop all containers before upgrading to a version of the runtime that used `/run/cc-oci-runtime/` to avoid getting into that situation.

**Comment by jodh-intel** [comment]
Note that this bug would have been found if a test for #72 existed. I'll look at that now...
