### ISSUE TITLE
Error using swarm image

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#313]
It is not possible to run the swarm image from docker hub using cc-oci-runtime
# docker run --rm swarm create
container-workload.service: Failed at step EXEC spawning /.containerexec: No such file or directory

**Comment by jodh-intel** [comment]
This is #95.

**Comment by gorozco1** [comment]
closed due duplicate #95

**Comment by grahamwhaley** [comment]
Actually, I think this might be different - this is the old method of running swarm, before it was integrated into docker. I think this is actually more like #222 - either way, a duplicate, so it can stay closed.
istr I looked into this one when somebody failed to run the 'swarm demo', as they were using this old method (the swarm image) rather than the new method (built in swarm).
