### ISSUE TITLE
docker swarm integration test

### ISSUE THREAD

**Issue by GabyCT** [01org/cc-oci-runtime#426]
multinetwork functionality

**Comment by grahamwhaley** [comment]
Hi @GabyCT.
 First, I'll note this feedback is not specific to just you or this Issue - this just happens to be the Issue that I had open...
 The subject line and message for this Issue are a little 'slim'. Can we try and be a little more verbose and detailed in the future Issue reports? Writing them with enough info and details so that somebody else can pick them up without having to ask further questions would be ideal I think.
 The subject line here is actually OK (the only think I may have done was write 'Add docker swarm integration tests' maybe :-)
 For the body of the Issue, it would be good if there were details, presuming we had some thoughts, on what we were going to test (multiple network interfaces or cross-container comms or similar for instance), and if we had thoughts on how or where then those details as well.

thanks!
/me notes to self that I should probably work on defining this a bit more and adding it to our CONTRIBUTING file...

**Comment by GabyCT** [comment]
closing this issue as all the tests merged
