### ISSUE TITLE
Console behaviour needs fixing

### ISSUE THREAD

**Issue by amshinde** [01org/cc-oci-runtime#444]
When run in interactive mode(docker run -it debian /bin/bash)
1) The console does not show a prompt. 
2) When you type a command (eg "ls -la" )and hit enter, the command ("ls -la")is returned back to the shim followed by the output of the command causing the command to be displayed again.
3) When you run a long running command like (top -b) and hit ctrl-c, the container itself exits instead of the command exiting. (I think we may need to disable signals for the terminal, and handle special characters ctrl-c and ctl-d by simply sending them on the I/O channel)

**Comment by chavafg** [comment]
Related to item 3 above (maybe you have already noticed): 
When trying to exit the container with `ctrl-d`, this error is shown and the container does not exit.
```
cc-shim[8297]: handle_stdin:298:Error while reading stdin char :Resource temporarily unavailable
```
exiting the container with `exit` works well.

**Comment by dlespiau** [comment]
So, I looked a bit at that. My guesses/investigation/thoughts so far:

- For the double line problem: what I think happens: the local pty has echo enabled and the remote pty also has echo enabled. So when typing a character, the local echo shows it and the the remote terminal echo writes to stdout as well, showing things twice

- You have copied TtyLiner from runv. I now think that's only for their debugging mode - hyperstart can have a telnet server listening and one can connect to that server to debug the VM (I believe so at least, not actually tested)

- Because of the above, the shim actually  buffers lines before sending them to the shim, which isn't a behaviour we want. we should probably just send the data we receive on stdio to hyperstart as soon as possible

- to solve things, I wonder how close we'd be in we put the local pty in raw mode and just forward input to hyperstart, still with a read of size 1.

- note: we may be able to do read with larger sizes in raw mode to optimise data transfers when stdin is used to pipe data.

**Comment by amshinde** [comment]
@dlespiau Looked into this. Realized that the /bin/sh behaves correctly. Have rootcaused the issue for bash. bash behaves weird because the stderr needs redirection. Will send out a fix.

**Comment by dlespiau** [comment]
Implemented my suggestion above in PR https://github.com/01org/cc-oci-runtime/pull/473, interactive programs are usable with that one.

**Comment by amshinde** [comment]
#476 fixes the missing prompt. Closing this.
