### ISSUE TITLE
shim calls killcontainer on exit signal

### ISSUE THREAD

**Issue by jcvenegas** [01org/cc-oci-runtime#493]
shim is a workload representation of a workload, we could have shim created from create command or exec.

If start shim call killcontainer all the other workloads will die, that it is a correct behivor acording to docker exec command [1].

But if an exec shim send a killcontainer message hyper start, all the workloads will be finished, inlcuded the workload created on "create workload", but actually only the exec workload must die.

[1]https://docs.docker.com/engine/reference/commandline/exec/

**Comment by amshinde** [comment]
Seems like we need something like a killexec command for hyperstart that kills an exec process based on the exec sequence number. The shim may call that based on whether it is called via exec/start.

**Comment by amshinde** [comment]
Tested this behaviour. 
```
$docker run --name deb-test -it debian
root@d2d8f2a7cc99

On separate terminal:
$docker exec deb-test top -b
^C
```

Turns out that Ctrl-C on an execed instance doesnt really send a signal to the execed process (in our case the shim spawned in the exec), and hence the shim  would never cause a killcontainer command to be delivered to hyperstart in this case.
Instead I see  the execed process (top -b) in the VM  continues to execute as seen by the proxy logs. 

I have seen similar behaviour with runc, as seen by the files left behind:
```
$ sudo ls /run/docker/libcontainerd/containerd/d2d8f2a7cc99974c68f961ce8118b114ba1e4bb74b76f13ceac0f22ec321d76e/9c2edf172c886b32dc6e456d7319ea30d0d0c85d482225681205347ad182ed0f/
control  exit  log.json  pid  process.json  shim-log.json
```
Only on running a shortlived process that exits immediately or running exit in an interactive exec instance, these files are cleaned up.

Considering that docker doesn't really forward signals to the execed process, I think we can close this one.
