### ISSUE TITLE
docker hello-world hangs up with -t

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#798]
Running the standard Docker hello-world example (https://hub.docker.com/_/hello-world/) with:
``` docker run -ti hello-world' ```
hangs up (run does not return).
If I then kill the run (has to be done from a separate terminal), and then try to `docker rm -f` the container that was created, that also hangs up.

This was under `ciao-down` (https://github.com/01org/ciao/tree/master/testutil/ciao-down), which installs Ubuntu 16.04.2 LTS, Docker 1.12.1 and Clear Containers 2.1.2

This is similar to the previous ticket #222 - but this hangs up rather than errors out. Note, on #222 2.1 'worked' with `docker run --rm -i hello-world`.  That command runs for me, but I do not see the output from the `hello-world` image, so I would classify that as not working? I would expect the `hello-world` functionality to be the same as when using the `runc` runtime.

@jodh-intel verified a hang up here. @jodh-intel , can you provide some system details if they are different from mine, for completeness.

**Comment by jodh-intel** [comment]
Hang (no output) seen under clr:

```
$ sudo swupd update -s
swupd-client software update 3.8.5
   Copyright (C) 2012-2016 Intel Corporation

Attempting to download version string to memory
Current OS version: 14380
Latest server version: 14380
$ cc-oci-runtime version
cc-oci-runtime version: 2.1.1
spec version: 1.0.0-rc1
commit: d7de93a13edc9eddf7d6417f20a6faa3f56136dc

```
Same behaviour as @grahamwhaley - the reason the `docker rm` hangs is because the hypervisor is still running. If that is killed, the container can be deleted.

Log files attached.

Notes:

- The `cc-proxy` log was generated using `script -c "cc-proxy -v 4"`.
- The last few lines of `cor.log` were cased by my killing `cc-proxy` manually
  (the last line written before the hang was for `created state file.*/state.json` on line 197).
---

[cor.log.txt](https://github.com/01org/cc-oci-runtime/files/902251/cor.log.txt)
[cc-proxy.typescript.txt](https://github.com/01org/cc-oci-runtime/files/902253/cc-proxy.typescript.txt)

**Comment by devimc** [comment]
@jodh-intel  great debug information
I'll take a look
Thanks

**Comment by devimc** [comment]
fix https://github.com/clearcontainers/hyperstart/pull/14

**Comment by devimc** [comment]
fixed clear container image 14590
