### ISSUE TITLE
Create CI pre-checks script to check git commits

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#872]
Create a script that performs basic checks on the new commits to be merged.

Script can check for things like a `Fixes #XXX` tag, subsystem in title, *etc*.

Script will be called as part of the CI workflow crucially before any setup/build/tests run.

See #856.

**Comment by grahamwhaley** [comment]
Re-opening due to: https://github.com/01org/cc-oci-runtime/pull/883
Let's discuss where we go from here...

**Comment by dlespiau** [comment]
Question: do we really need to enforce line length on commit messages? In the general case, I can see pasting backtraces and logs in commit messages failing that test, but it that a problem?

The fixes check seems useful on stable branches though.

Something I noted is that these kind of things could benefit from unit testing with a variety input commit messages. Not necessarily suggesting we go full on (written in go with unit test).

**Comment by grahamwhaley** [comment]
I agree, the line length check is probably not going to work for pasted items etc. - and, it's going to be pretty hard to get the script to recognise what is hand typed and what is pasted.
Really really really I'd like the script to be able to issue a `Warning` rather than fail the CI. I don't believe there is a native way to post some sort of warning to github, but we could get the script to inject a Comment back to the PR (like we have the `qa-passed` injected. @jodh-intel and I briefly discussed that a little already. One thing I can see might not work there is having the 'robot' user token held in public view in the CI system though :-(

You are suggesting writing unit tests for the CI script, yes @dlespiau - yeah, I can see that. Knowing @jodh-intel penchant for tests, I'm surprised he didn't already have some :-)

**Comment by jodh-intel** [comment]
Oops - sorry @jcvenegas! :smile:

This is indeed tricky territory. I suggest we introduce some simple rules to both handle line lengths *and* allow us to paste logs, mails and keep the process low-impact:

The rules are:

1. The script will only check the line length **if the line starts with an alphabetic character**.

    This has some nice properties:

    - If you want the script to ignore anything "special", you can simply add an inden (useful for things like logs / backtraces / *etc*).
    - You can paste email/issue conversations *unindented* in the usual "prefixed-by-greater-than" format:
      ```
      > I am part of a conversation so won't be checked.
      ```
    - You'll actually be able to paste logs *unindented* as they start with a timestamp ;-)

1. The script won't check the line length for a `Signed-off-by:` line.

1. The script may special-case non-PR branches.

@grahamwhaley - I didn't write any tests for this script, but I did test it (honest guv!). Clearly, I should have delegated that work to @jcvenegas though ;-)

@dlespiau - I think you are right - this would be better in go (probably safer too). I'm now inspired to rewrite the script in go and add some proper tests...

**Comment by jodh-intel** [comment]
Closing as this is now tracked on https://github.com/clearcontainers/tests/issues/18.
