### ISSUE TITLE
Make it easier to install autoconf-archive m4 macros

### ISSUE THREAD

**Issue by grahamwhaley** [01org/cc-oci-runtime#875]
Now we have removed the m4 macros we had extracted from the autoconf-archive, and rely on either the host system having them pre-installed or for an installation script to install them by hand if necessary (such as seen here https://github.com/01org/cc-oci-runtime/blob/master/installation/rhel-setup.sh#L161), there are times during development when you'd just like to do that curl hand install 'by hand'. Thus, it would be good to extract that 'curl magic' into a separate script that can be both utilised by the install scripts as per above, or run by hand before a configure to get the relevant macros installed in place.

**Comment by dlespiau** [comment]
What about making installing that new build dependency as part of autogen.sh? that's the script supposed to bootstrap the build system after all.

**Comment by jodh-intel** [comment]
That's an interesting point. I've always seen `autogen.sh` as something that attempts to make the source buildable, crucially without changing the system state. It might be rather unexpected if that script starts installing packages.

Maybe a compromise could be to add a `--make-it-so`-type option. If not specified, `autogen.sh` will be have like it does now and fail if dependencies are not installed (but also make mention of the new option). If that new option is specified, the script will attempt to install missing packages.

Note that in the latter case, we'd have to add in distro-specific commands to install the packaged `autoconf-archive`, or download if not available. In fact, we'd also need to rework the `.ci/` and the `installation/` scripts since they call `autogen.sh` and have `autogen.sh` source files as appropriate.
Finally, the docs will need to be updated to take account of such changes (including detailing the new `--make-it-so`-type option).
